//export const PRODUCT_CATEGORY = 'PRODUCT_CATEGORY'
//export const PRODUCT_ITEM = 'PRODUCT_ITEM'
//export const FILTER_PRODUCT = 'FILTER_PRODUCT'

export enum ActionTypes {
    PRODUCT_CATEGORY = 'PRODUCT_CATEGORY',
    PRODUCT_ITEM = 'PRODUCT_ITEM',
    FILTER_PRODUCT = 'FILTER_PRODUCT'
}